name: Configure Bazel Remote Cache Authentication
description: |
  Writes Bazel settings for Bazel remote cache authentication/upload to a bazelrc file.

inputs:
  remote_header:
    type: string
    description: The value that is written for Bazel's --remote_header flag.
  buildbuddy_api_key:
    type: string
    description: |
      The API key that provides access to BuildBuddy's remote cache service. If a value is not 
      specified for remote-header, one will be created using the value of this input.
  bazelrc_path:
    type: string
    description: The path to the bazelrc file to be updated.
    default: ".bazelrc"
  checkout_path:
    type: string
    default: .github/actions/configure-bazel-remote-cache-auth

runs:
  using: composite
  steps:
    # - name: Checkout this repository
    #   uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    #   with:
    #     repository: tweag/configure-bazel-remote-cache-auth
    #     ref: ${{ inputs.checkout_ref }}
    #     path: ${{ inputs.checkout_path }}

    - shell: bash
      env:
        REMOTE_HEADER: ${{ inputs.remote_header }}
        BUILDBUDDY_API_KEY: ${{ inputs.buildbuddy_api_key }}
        BAZELRC_PATH: ${{ inputs.bazelrc_path }}
      run: |
        find . | sort
