name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  - name: Checkout the repository
    uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

  - name: Execute the unit tests
    shell: bash
    run: |
      bazelisk test //...

